# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name_plural': '06.专题课或学位课模块'},
        ),
    ]
